### ISSUE TITLE
AttributeError: 'CustomMultiTaskRLBenchEnv2' object has no attribute 'get_ground_truth_action'

### ISSUE THREAD

**Issue by rakhimovv** [NVlabs/RVT#35]
Hello, thank you for the wonderful work!

I would like to check demos saved. For this I run the following script:

`python eval.py --model-folder runs/rvt  --eval-datafolder ./data/val --tasks close_jar --eval-episodes 25 --log-name val/1 --device 0 --model-name model_14.pth --save-video --ground-truth`

It fails with the following error:
```
Traceback (most recent call last):
  File "/home/projects/RVT/rvt/eval.py", line 540, in <module>
    _eval(args)
  File "/home/projects/RVT/rvt/eval.py", line 494, in _eval
    scores = eval(
  File "/home/miniconda3/envs/rvt/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/projects/RVT/rvt/eval.py", line 284, in eval
    raise e
  File "/home/projects/RVT/rvt/eval.py", line 278, in eval
    for replay_transition in generator:
  File "/home/projects/RVT/rvt/libs/YARR/yarr/utils/rollout_generator.py", line 43, in generator
    actions = env.get_ground_truth_action(eval_demo_seed)
AttributeError: 'CustomMultiTaskRLBenchEnv2' object has no attribute 'get_ground_truth_action'
```

**Comment by imankgoyal** [comment]
Hi, 

Thanks for your interest in our work. Unfortunately, this functionality is not supported in the released code. I guess, you might have to extend parts of `CustomMultiTaskRLBenchEnv2` to get this working.

Best,
Ankit
